#!/usr/bin/env node
// Bundles the SVG path data for exactly the brand icons src/lib/techIcons.js
// names, so the app renders logos with no third-party CDN request.
// Run: npm run icons  (also runs as part of npm run build)
const fs = require("fs");
const path = require("path");
const si = require("simple-icons");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src", "lib", "techIcons.js");
const OUT = path.join(ROOT, "src", "lib", "iconPaths.js");

const bySlug = new Map();
for (const icon of Object.values(si)) if (icon && icon.slug) bySlug.set(icon.slug, icon);

const slugs = [...new Set([...fs.readFileSync(SRC, "utf8").matchAll(/\[\s*"([a-z0-9.-]+)"\s*,\s*"[0-9A-Fa-f]{6}"\s*\]/g)].map(m => m[1]))];

const found = {}, missing = [];
for (const slug of slugs) {
  const icon = bySlug.get(slug);
  if (icon) found[slug] = icon.path; else missing.push(slug);
}

fs.writeFileSync(OUT,
  "// GENERATED by scripts/build-icons.cjs — do not edit.\n" +
  "// SVG path data for the brand icons named in techIcons.js, from `simple-icons`.\n" +
  "export const ICON_PATHS = " + JSON.stringify(found, null, 0) + ";\n");

console.log(`icons: ${Object.keys(found).length} bundled${missing.length ? `, ${missing.length} unresolved -> letter tile: ${missing.join(", ")}` : ""}`);
